name: Pull Request Validation

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Validate PR Title
        run: |
          node .github/scripts/validate-pr-title.js ${{ github.event.pull_request.title }}
